# Generated by Django 3.2.15 on 2022-08-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='bonuses',
            field=models.IntegerField(default=0, verbose_name='Бонусы'),
        ),
        migrations.AlterField(
            model_name='users',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='users',
            name='secondname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
