# Generated by Django 3.2.15 on 2022-09-04 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=255)),
                ('apartment', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('contactless', models.BooleanField()),
                ('price', models.CharField(max_length=50)),
                ('goods', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('paid', models.BooleanField()),
                ('is_delivery', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя категории')),
            ],
            options={
                'verbose_name': 'Категории продуктов',
                'verbose_name_plural': 'Категории продуктов',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Имя товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.TextField(verbose_name='Картинка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.productscategories', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
                'ordering': ['category'],
            },
        ),
    ]
