# Generated by Django 3.2.15 on 2022-08-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('is_need_delivery', models.BooleanField()),
                ('address', models.CharField(max_length=255)),
                ('apartment', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('contactless', models.BooleanField()),
                ('price', models.IntegerField()),
                ('goods', models.TextField()),
            ],
        ),
    ]
