# Generated by Django 3.2.15 on 2022-09-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=70)),
                ('secondname', models.CharField(max_length=70)),
                ('phone', models.IntegerField()),
                ('status', models.CharField(max_length=70)),
                ('last_completed_order', models.DateTimeField(null=True)),
                ('card_number', models.CharField(max_length=70)),
                ('hours_worked', models.IntegerField()),
            ],
        ),
    ]
