# Generated by Django 3.2.15 on 2022-09-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_orders_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='point_pk',
            field=models.IntegerField(default=0),
        ),
    ]
